### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by AstroSquared** [GeorgeRNG/NoUtilities#1]
Github isn't letting me commit to my fork or create a pr so uh yeah

To fix the issue add a space between the `#` and `NoUtilities`

**Comment by GeorgeRNG** [comment]
Perhaps you have my version of the repo cloned, not your fork.
Anyway, if you select a file you can edit it even in other repositories and if you can't write to it, it will make a fork/pr

**Comment by AstroSquared** [comment]
I edited the file in this repo and propose changes was grayed out
I tried on my fork too

**Comment by CheaterTim** [comment]
B
